/*
 * Copyright (c) 2023 Huawei Device Co., Ltd.
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */
#include "preset_type_descriptors.h"
namespace OHOS {
namespace UDMF {
PresetTypeDescriptors::PresetTypeDescriptors()
{
    InitDescriptors();
}

PresetTypeDescriptors::~PresetTypeDescriptors()
{
}

PresetTypeDescriptors &PresetTypeDescriptors::GetInstance()
{
    static auto instance = new PresetTypeDescriptors();
    return *instance;
}

std::vector<TypeDescriptor> &PresetTypeDescriptors::GetTypeDescriptors()
{
    return typeDescriptors_;
}

void PresetTypeDescriptors::InitDescriptors()
{
    typeDescriptors_ = {
        {"general.database",
         {},
         {},
         {},
         "Base type for databases.",
         "",
         ""},
        {"general.message",
         {},
         {},
         {},
         "Base type for messages (email, IM, and so on).",
         "",
         ""},
        {"general.contact",
         {},
         {},
         {},
         "Base type for contact information.",
         "",
         ""},
        {"general.archive",
         {},
         {},
         {},
         "Base type for an archive of files and directories.",
         "",
         ""},
        {"general.disk-image",
         {"general.archive"},
         {},
         {},
         "Base type for items mountable as a volume.",
         "",
         ""},
        {"general.text",
         {},
         {},
         {},
         "Base type for all text, including text with markup information (HTML, RTF, and so on).",
         "",
         ""},
        {"general.plain-text",
         {"general.text"},
         {".txt"},
         {"text/plain"},
         "Text of unspecified encoding, with no markup. Equivalent to the MIME type text/plain",
         "",
         ""},
        {"general.html",
         {"general.text"},
         {".html", ".htm"},
         {"text/html"},
         "HTML text.",
         "",
         ""},
        {"general.xml",
         {"general.text"},
         {".xml"},
         {"text/xml"},
         "XML text.",
         "",
         ""},
        {"general.source-code",
         {"general.plain-text"},
         {},
         {},
         "Generic source code.",
         "",
         ""},
        {"general.c-source",
         {"general.source-code"},
         {".c"},
         {},
         "C source code.",
         "",
         ""},
        {"general.c-plus-plus-source",
         {"general.source-code"},
         {".cp", ".cpp", ".c++", ".cc", ".cxx"},
         {},
         "C++ source code.",
         "",
         ""},
        {"general.c-header",
         {"general.source-code"},
         {".h"},
         {},
         "C header file.",
         "",
         ""},
        {"general.c-plus-plus-header",
         {"general.source-code"},
         {".hpp", ".h++", ".hxx"},
         {},
         "C++ header file.",
         "",
         ""},
        {"general.script",
         {"general.source-code"},
         {},
         {},
         "Base type for scripting language source code.",
         "",
         ""},
        {"general.shell-script",
         {"general.script"},
         {".sh", ".command"},
         {},
         "Shell script.",
         "",
         ""},
        {"general.csh-script",
         {"general.shell-script"},
         {".csh"},
         {},
         "C-shell script.",
         "",
         ""},
        {"general.perl-script",
         {"general.shell-script"},
         {".pl", ".pm"},
         {"text/x-perl-script"},
         "Perl script.",
         "",
         ""},
        {"general.python-script",
         {"general.shell-script"},
         {".py"},
         {"text/x-python-script"},
         "Python script.",
         "",
         ""},
        {"general.ruby-script",
         {"general.shell-script"},
         {".rb", ".rbw"},
         {"text/ruby-script"},
         "Ruby script.",
         "",
         ""},
        {"general.php-script",
         {"general.shell-script"},
         {".php", ".php3", ".php4", ".ph3", ".ph4", ".phtml"},
         {"text/x-php-script, text/php, application/php"},
         "PHP script.",
         "",
         ""},
        {"general.tar-archive",
         {"general.archive"},
         {".tar"},
         {"application/x-tar, application/tar"},
         "Tar archive.",
         "",
         ""},
        {"general.vcard",
         {},
         {},
         {},
         "Base type for electronic business card.",
         "",
         ""},
        {"general.image",
         {"general.media"},
         {},
         {},
         "Base type for images.",
         "",
         ""},
        {"general.jpeg",
         {"general.image"},
         {".jpg", ".jpeg"},
         {"image/jpeg"},
         "JPEG image.",
         "",
         ""},
        {"general.tiff",
         {"general.image"},
         {".tif", ".tiff"},
         {"image/tiff"},
         "TIFF image.",
         "",
         ""},
        {"general.raw-image",
         {"general.image"},
         {},
         {},
         "Base type for digital camera raw image formats.",
         "",
         ""},
        {"general.png",
         {"general.image"},
         {".png"},
         {"image/png"},
         "PNG image",
         "",
         ""},
        {"general.video",
         {"general.media"},
         {},
         {},
         "Base type for video.",
         "",
         ""},
        {"general.avi",
         {"general.video"},
         {".avi", ".vfw"},
         {"video/avi", "video/msvideo", "video/x-msvideo"},
         "AVI video.",
         "",
         ""},
        {"general.mpeg",
         {"general.video"},
         {".mpg", ".mpeg"},
         {"video/mpg", "video/mpeg", "video/x-mpg", "video/x-mpeg"},
         "MPEG-1 or MPEG-2 video.",
         "",
         ""},
        {"general.mpeg-4",
         {"general.video"},
         {".mp4"},
         {"video/mp4", "video/mp4v"},
         "MPEG-4 video.",
         "",
         ""},
        {"general.3gpp",
         {"general.video"},
         {".3gp", ".3gpp"},
         {"video/3gpp"},
         "3GPP video.",
         "",
         ""},
        {"general.3gpp2",
         {"general.video"},
         {".3g2", ".3gp2"},
         {"video/3gpp2"},
         "3GPP2 video.",
         "",
         ""},
        {"general.audio",
         {"general.media"},
         {},
         {},
         "Base type for audio.",
         "",
         ""},
        {"general.mp3",
         {"general.audio"},
         {".mp3,"},
         {"audio/mp3"},
         "MPEG-3 audio.",
         "",
         ""},
        {"general.aac",
         {"general.audio"},
         {".aac"},
         {"audio/aac"},
         "AAC audio.",
         "",
         ""},
        {"general.aiff",
         {"general.audio"},
         {".aiff"},
         {"audio/aiff"},
         "AIFF audio.",
         "",
         ""},
        {"general.alac",
         {"general.audio"},
         {".alac"},
         {"audio/alac"},
         "ALAC audio.",
         "",
         ""},
        {"general.bz2-archive",
         {"general.archive"},
         {".bz2"},
         {"application/x-bzip2"},
         "BZip2 archive.",
         "",
         ""},
        {"general.calendar",
         {},
         {},
         {},
         "Base type for scheduled events.",
         "",
         ""},
        {"general.ebook",
         {},
         {},
         {},
         "Base type for ebook.",
         "",
         ""},
        {"general.epub",
         {"general.ebook"},
         {".epub"},
         {"application/epub+zip"},
         "Electronic publication (EPUB) format.",
         "",
         ""},
        {"general.flac",
         {"general.audio"},
         {".flac"},
         {"audio/flac"},
         "FLAC audio.",
         "",
         ""},
        {"general.java-script",
         {"general.source-code"},
         {".js", ".jscript", ".javascript"},
         {"text/javascript"},
         "",
         "",
         ""},
        {"general.java-source",
         {"general.source-code"},
         {".java", ".jav"},
         {},
         "Java source code.",
         "",
         ""},
        {"general.location",
         {"general.navigation"},
         {},
         {},
         "Navigation location.",
         "",
         ""},
        {"general.media",
         {},
         {},
         {},
         "Base type for media.",
         "",
         ""},
        {"general.navigation",
         {},
         {},
         {},
         "Base type for navigation.",
         "",
         ""},
        {"general.ogg",
         {"general.audio"},
         {".ogg"},
         {"audio/ogg"},
         "OGG audio.",
         "",
         ""},
        {"general.pcm",
         {"general.audio"},
         {".pcm"},
         {"audio/pcm"},
         "PCM audio.",
         "",
         ""},
        {"general.type-script",
         {"general.source-code"},
         {".ts"},
         {},
         "TypeScript source code.",
         "",
         ""},
        {"general.zip-archive",
         {"general.archive"},
         {".zip"},
         {"application/zip"},
         "Zip archive.",
         "",
         ""},
        {"general.hyperlink",
         {"general.text"},
         {},
         {},
         "Hyperlink.",
         "",
         ""},
        {"general.file",
         {},
         {},
         {},
         "Base type for file.",
         "",
         ""},
        {"general.directory",
         {},
         {},
         {},
         "Base type for directory.",
         "",
         ""},
        {"general.folder",
         {},
         {},
         {},
         "Base type for folder.",
         "",
         ""},
        {"general.symlink",
         {},
         {},
         {},
         "Base type for symlink.",
         "",
         ""},
        {"com.adobe.pdf",
         {},
         {".pdf"},
         {"application/pdf"},
         "PDF data.",
         "",
         ""},
        {"com.adobe.postscript",
         {},
         {".ps"},
         {"application/postscript"},
         "PostScript data.",
         "",
         ""},
        {"com.adobe.encapsulated-postscript",
         {},
         {".eps"},
         {},
         "Encapsulated PostScript.",
         "",
         ""},
        {"com.adobe.photoshop-image",
         {"general.image"},
         {".psd"},
         {"image/x-photoshop", "image/photoshop", "image/psd", "application/photoshop"},
         "Adobe Photoshop document.",
         "",
         ""},
        {"com.adobe.illustrator.ai-image",
         {"general.image"},
         {".ai"},
         {},
         "Adobe Illustrator document.",
         "",
         ""},
        {"com.microsoft.bmp",
         {"general.image"},
         {".bmp"},
         {},
         "Windows bitmap image.",
         "",
         ""},
        {"com.microsoft.ico",
         {"general.image"},
         {".ico"},
         {},
         "Windows icon image.",
         "",
         ""},
        {"com.microsoft.word.doc",
         {},
         {".doc"},
         {"application/msword"},
         "Microsoft Word data.",
         "",
         ""},
        {"com.microsoft.excel.xls",
         {},
         {".xls"},
         {"application/vnd.ms-excel"},
         "Microsoft Excel data.",
         "",
         ""},
        {"com.microsoft.powerpoint.ppt",
         {},
         {".ppt"},
         {"application/mspowerpoint"},
         "Microsoft PowerPoint presentation.",
         "",
         ""},
        {"com.microsoft.waveform-audio",
         {"general.audio"},
         {".wav", ".wave", ".WAV"},
         {"audio/wav", "audio/wave"},
         "Waveform audio.",
         "",
         ""},
        {"com.microsoft.windows-media-wm",
         {"general.video"},
         {".wm"},
         {"video/x-ms-wm"},
         "Windows WM video.",
         "",
         ""},
        {"com.microsoft.windows-media-wmv",
         {"general.video"},
         {".wmv"},
         {"video/x-ms-wmv"},
         "Windows WMV video.",
         "",
         ""},
        {"com.microsoft.windows-media-wmp",
         {"general.video"},
         {".wmp"},
         {"video/x-ms-wmp"},
         "Windows WMP video.",
         "",
         ""},
        {"com.microsoft.windows-media-wma",
         {"general.audio"},
         {".wma"},
         {"video/x-ms-wma"},
         "Windows WMA audio.",
         "",
         ""},
        {"com.microsoft.windows-media-wmx",
         {"general.audio"},
         {".wmx"},
         {"video/x-ms-wmx"},
         "Windows WMX audio.",
         "",
         ""},
        {"com.microsoft.windows-media-wvx",
         {"general.audio"},
         {".wvx"},
         {"video/x-ms-wvx"},
         "Windows WVX audio.",
         "",
         ""},
        {"com.microsoft.windows-media-wax",
         {"general.audio"},
         {".wax"},
         {"video/x-ms-wax"},
         "Windows WAX audio.",
         "",
         ""},
        {"com.amazon.azw",
         {"general.ebook"},
         {".azw"},
         {"application/vnd.amazon.ebook"},
         "AZW ebook.",
         "",
         ""},
        {"com.amazon.azw3",
         {"general.ebook"},
         {".azw3"},
         {"application/vnd.amazon.mobi8-ebook", "application/x-mobi8-ebook"},
         "AZW3 ebook.",
         "",
         ""},
        {"com.amazon.kfx",
         {"general.ebook"},
         {".kfx"},
         {},
         "KFX ebook.",
         "",
         ""},
        {"com.amazon.mobi",
         {"general.ebook"},
         {".mobi"},
         {"application/x-mobipocket-ebook"},
         "MOBI ebook.",
         "",
         ""},
        {"com.sun.java-archive",
         {"general.archive"},
         {".jar"},
         {"application/java-archive"},
         "Java archive.",
         "",
         ""},
        {"org.gnu.gnu-tar-archive",
         {"general.archive"},
         {".gtar"},
         {"application/x-gtar"},
         "GNU archive.",
         "",
         ""},
        {"org.gnu.gnu-zip-archive",
         {"general.archive"},
         {".gz", ".gzip"},
         {"application/x-gzip", "application/gzip"},
         "Gzip archive.",
         "",
         ""},
        {"org.gnu.gnu-zip-tar-archive",
         {"general.archive"},
         {".tgz"},
         {},
         "Gzip tar archive.",
         "",
         ""},
        {"openharmony.form",
         {},
         {},
         {},
         "OpenHarmony system defined form.",
         "",
         ""},
        {"openharmony.app-item",
         {},
         {},
         {},
         "OpenHarmony system defined app item.",
         "",
         ""},
        {"openharmony.pixel-map",
         {},
         {},
         {},
         "OpenHarmony system defined pixel map.",
         "",
         ""},
        {"openharmony.atomic-service",
         {},
         {},
         {},
         "OpenHarmony system defined atomic service.",
         "",
         ""}
    };
}
} // namespace UDMF
} // namespace OHOS